### ISSUE TITLE
$o-theme-color-palettes are not used

### ISSUE THREAD

**Issue by jwaes** [odoo/design-themes#553]
Most of the themes define (overrule) color-palettes.
For example:
https://github.com/odoo/design-themes/blob/15.0/theme_monglia/static/src/scss/primary_variables.scss

```
$o-theme-color-palettes: map-merge($o-theme-color-palettes,
    (
        'monglia-1': (
            'alpha': #ffffff,
            'beta': #add3ce,
            'gamma': #a7c7d5,
            'delta': #47464b,
            'epsilon': #f3997b,
```

To my understanding, this should overwrite the pre-defined value from 
https://github.com/odoo/odoo/blob/15.0/addons/website/static/src/scss/primary_variables.scss

```
        'monglia-1': (
            'o-color-1': #ed145b,
            'o-color-2': #9CD6FA,
            'o-color-3': #f5f5f5,
            'o-color-4': #ffffff,
            'o-color-5': #111111,

            'copyright-custom': 'black-15',
```

But it does not, the color values form website are used, not the ones from the theme itself.

![image](https://user-images.githubusercontent.com/50528773/157457378-ff5e257e-4b26-4d0e-8a75-dfef99e2cfc0.png)

Furthermore, i do not understand why the theme defines a whole list of color pallets, which do not get used anywhere, are not added to the Theme color picker in the UI and are not 'reachable' at all.

Given the fact that Odoo does not provide up to date documentation on how to create themes for v15, I try to build a theme based on these Odoo repository themes.
But this approach is faulty because it totally depends on color-palettes that need to exist in "addons/website/static/src/scss/primary_variables.scss" 
What is the use of theme modules if they are not 'stand-alone' ?

**Comment by qsm-odoo** [comment]
Hello @jwaes

> Given the fact that Odoo does not provide up to date documentation on how to create themes for v15, I try to build a theme based on these Odoo repository themes.

We are sorry about that. A lot of work has been done over the past years to make the editor and themes grow fast and indeed, our documentation about all of this simply does not exist. It is still something I would really really like to update as soon as possible.

I'll try to give you some pointers, hopefully this can help you.

> Most of the themes define (overrule) color-palettes.
> For example:
> https://github.com/odoo/design-themes/blob/15.0/theme_monglia/static/src/scss/primary_variables.scss
> To my understanding, this should overwrite the pre-defined value from
> https://github.com/odoo/odoo/blob/15.0/addons/website/static/src/scss/primary_variables.scss

Actually no, this is not an overritte at all. The code in standard odoo you refer updates the map `$o-color-palettes` while the theme code you refer to updates the map `$o-theme-color-palettes`. These are two different maps which are linked to the bootstrap related ones: `$colors` and `$theme-colors`. When you have the `'monglia-1'` you mention enabled, you have the values from both maps and they are not used for the same things.

> the color values form website are used, not the ones from the theme itself. Furthermore, i do not understand why the theme defines a whole list of color pallets, which do not get used anywhere, are not added to the Theme color picker in the UI and are not 'reachable' at all.

Actually, this is a very specific case you mention (most themes don't do that). The alpha -> epsilon keys in the theme palette are there for compatibility of old websites (<= 13.0). The goal is that this code may be removed at some point. But an user which starts with version 15.0 totally ignores that code as the alpha -> epsilon keys are removed in the end if the database does not come from <= 13.0.

> But this approach is faulty because it totally depends on color-palettes that need to exist in "addons/website/static/src/scss/primary_variables.scss"
> What is the use of theme modules if they are not 'stand-alone' ?

I am not sure what you mean by "standalone", a theme of course needs the website app to installed and will thus always depend on it and never be standalone. However, a theme can do anything you want and does not need a color palette to exist in the website file as you mention. You can simply extend the `$o-color-palettes` map of website with yours, in the theme file (you probably tried to extend the `$o-theme-color-palettes` ones which is not the same one as explained above). So, in your theme file, you can do exactly as it is done in the website file:
- adding palettes: https://github.com/odoo/odoo/blob/15.0/addons/website/static/src/scss/primary_variables.scss#L47
- adding it to the list of what is shown in the editor: https://github.com/odoo/design-themes/blob/15.0/theme_monglia/static/src/scss/primary_variables.scss#L157 (we have many not shown... for compatibility with old websites)
- choosing the one which is used by default: https://github.com/odoo/design-themes/blob/15.0/theme_monglia/static/src/scss/primary_variables.scss#L138

So for our own Odoo themes, most (all) of the color definition, CSS rules, etc are defined in website. That is to have the possibility to share them across themes and ease maintenance. But an external module as yours as not restriction to what you can do... unfortunately this indeed needs a way better doc.

We are also working on a refactoring to simplify all of this and ease theme definitions for external developers... but no guarantee. In any case, be sure a documentation will come :+1: 

Hope this helps anyway !
